behaviors:
  Freddingus:
    trainer_type: sac
    threaded: true
    hyperparameters:
      learning_rate: 0.00015
      learning_rate_schedule: constant
      batch_size: 512
      buffer_size: 2000000
      buffer_init_steps: 20480
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.01
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: false
      hidden_units: 1024
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 2.0
    keep_checkpoints: 5
    max_steps: 42000000
    time_horizon: 8192
    summary_freq: 81920
