behaviors:
  BattleBotDingusShover:
    trainer_type: ppo
    threaded: false
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.012
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 80
    summary_freq: 100000
  BattleBotDingusBomber:
    trainer_type: ppo
    threaded: false
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.012
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 80
    summary_freq: 100000
  BattleBotDingusDriller:
    trainer_type: ppo
    threaded: false
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.012
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 80
    summary_freq: 100000
  BattleBotDingusCharger:
    trainer_type: ppo
    threaded: false
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.012
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 80
    summary_freq: 100000
  BattleBotDingusHorner:
    trainer_type: ppo
    threaded: false
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.012
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 80
    summary_freq: 100000
  BattleBotDingusPlumber:
    trainer_type: ppo
    threaded: false
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.012
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 80
    summary_freq: 100000
  BattleBotDingusShooter:
    trainer_type: ppo
    threaded: false
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.012
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 80
    summary_freq: 100000
  BattleBotDingusSisyphus:
    trainer_type: ppo
    threaded: false
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.012
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 80
    summary_freq: 100000
  BattleBotDingusSniper:
    trainer_type: ppo
    threaded: false
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.012
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 80
    summary_freq: 100000
  BattleBotDingusGunslinger:
    trainer_type: ppo
    threaded: false
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.012
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 80
    summary_freq: 100000
  BattleBotDingusAssassin:
    trainer_type: ppo
    threaded: false
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.012
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 80
    summary_freq: 100000
  BattleBotDingusVacuum:
    trainer_type: ppo
    threaded: false
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.012
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 80
    summary_freq: 100000