behaviors:
  Escape:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 61440
      learning_rate: 0.0003
      beta: 0.015
      epsilon: 0.15
      lambd: 0.98
      num_epoch: 7
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 1536
      num_layers: 3
      vis_encode_type: simple
      memory:
        sequence_length: 160         # Long enough for multi-step tasks
        memory_size: 512
    reward_signals:
      extrinsic:
        gamma: 0.998
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 200000000
    time_horizon: 600
    summary_freq: 128000
