behaviors:
  JumpyOverBoi:
    trainer_type: ppo
    threaded: true
    hyperparameters:
      batch_size: 4096
      buffer_size: 12288
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.04
        network_settings:
          hidden_units: 256
        learning_rate: 0.0003
    keep_checkpoints: 100
    max_steps: 8000000
    time_horizon: 1024
    summary_freq: 20000
