behaviors:
  BattleBotDingusShover:
    trainer_type: poca
    threaded: true
    hyperparameters:
      batch_size: 3072
      buffer_size: 30720
      learning_rate: 0.0003
      beta: 0.004
      epsilon: 0.2
      lambd: 0.94
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.992
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 128
    summary_freq: 100000
  BattleBotDingusShooter:
    trainer_type: poca
    threaded: true
    hyperparameters:
      batch_size: 3072
      buffer_size: 30720
      learning_rate: 0.0003
      beta: 0.004
      epsilon: 0.2
      lambd: 0.94
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.992
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 128
    summary_freq: 100000
  BattleBotDingusCharger:
    trainer_type: poca
    threaded: true
    hyperparameters:
      batch_size: 3072
      buffer_size: 30720
      learning_rate: 0.0003
      beta: 0.004
      epsilon: 0.2
      lambd: 0.94
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.992
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 128
    summary_freq: 100000
  BattleBotDingusBomber:
    trainer_type: poca
    threaded: true
    hyperparameters:
      batch_size: 3072
      buffer_size: 30720
      learning_rate: 0.0003
      beta: 0.004
      epsilon: 0.2
      lambd: 0.94
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.992
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 128
    summary_freq: 100000
  BattleBotDingusSisyphus:
    trainer_type: poca
    threaded: true
    hyperparameters:
      batch_size: 3072
      buffer_size: 30720
      learning_rate: 0.0003
      beta: 0.004
      epsilon: 0.2
      lambd: 0.94
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.992
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 128
    summary_freq: 100000
  BattleBotDingusDriller:
    trainer_type: poca
    threaded: true
    hyperparameters:
      batch_size: 3072
      buffer_size: 30720
      learning_rate: 0.0003
      beta: 0.004
      epsilon: 0.2
      lambd: 0.94
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.992
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 128
    summary_freq: 100000
  BattleBotDingusHorner:
    trainer_type: poca
    threaded: true
    hyperparameters:
      batch_size: 3072
      buffer_size: 30720
      learning_rate: 0.0003
      beta: 0.004
      epsilon: 0.2
      lambd: 0.94
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.992
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 128
    summary_freq: 100000
  BattleBotDingusWaller:
    trainer_type: poca
    threaded: true
    hyperparameters:
      batch_size: 3072
      buffer_size: 30720
      learning_rate: 0.0003
      beta: 0.004
      epsilon: 0.2
      lambd: 0.94
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 128
    summary_freq: 100000
  BattleBotDingusPlumber:
    trainer_type: poca
    threaded: true
    hyperparameters:
      batch_size: 3072
      buffer_size: 30720
      learning_rate: 0.0003
      beta: 0.004
      epsilon: 0.2
      lambd: 0.94
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.992
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 128
    summary_freq: 100000
  BattleBotDingusSniper:
    trainer_type: poca
    threaded: true
    hyperparameters:
      batch_size: 3072
      buffer_size: 30720
      learning_rate: 0.0003
      beta: 0.004
      epsilon: 0.2
      lambd: 0.94
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.992
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 128
    summary_freq: 100000
